title: "Whatchacallit med  - Documentation"
remote_theme: pmarsceill/just-the-docs

# see https://pmarsceill.github.io/just-the-docs/docs/configuration/


color_scheme: "light"
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "Whatchacallit on GitHub":
    - "//github.com/whatchacallit"