title: "Whatchacallit med "
remote_theme: pmarsceill/just-the-docs

# see https://pmarsceill.github.io/just-the-docs/docs/configuration/


color_scheme: "light"
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "Whatchacallit on GitHub":
    - "//github.com/whatchacallit"

heading_anchors: false


footer_content: "Copyright &copy; the Contributors. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

